---
format_version: 10
pipelines:
  gocd-test-v3:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-bb61f68:
        git: https://github.com/Devin-Taylor/gocd-test.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - build-container:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            build:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -c
                      - docker build -t test-build-$(git rev-parse HEAD) .
                    command: /bin/zsh
                    run_if: passed
      - formatting:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            black-formatting:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -c 
                      - docker run test-build-$(git rev-parse HEAD) black --check ./src
                    command: /bin/zsh
                    run_if: passed
      - args-sorting:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            isort-sorting:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -c 
                      - docker run test-build-$(git rev-parse HEAD) isort --check-only ./src
                    command: /bin/zsh
                    run_if: passed
      - linting:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            flake8-linting:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -c 
                      - docker run test-build-$(git rev-parse HEAD) flake8 ./src
                    command: /bin/zsh
                    run_if: passed

