---
format_version: 10
pipelines:
  gocd-test:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-bb61f68:
        git: https://github.com/Devin-Taylor/gocd-test.git
        shallow_clone: false
        auto_update: true
        branch: develop
    stages:
      - formatting:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            black-formatting:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - --check
                      - ./src
                    command: black
                    run_if: passed
      - args-sorting:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            isort-sorting:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ./src
                      - -v
                      - --check-only
                    command: isort
                    run_if: passed
      - linting:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            flake8-linting:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ./src
                    command: flake8
                    run_if: passed
